version: "3.9"

services:
  spark:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: spark-lakehouse
    volumes:
      - ./data_lake:/app/data_lake
      - ./sensors:/app/sensors
      - ./spark:/app/spark
    stdin_open: true
    tty: true
