version: "3.9"

services:
  spark:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: spark-lakehouse
    volumes:
      - ./data_lake:/app/data_lake
      - ./spark:/app/spark
      - ./sensors:/app/sensors
    ports:
      - "4040:4040"
      - "8181:8080"
    environment:
      - SPARK_MODE=master
    stdin_open: true
    tty: true
    command: tail -f /dev/null
